# Dockerfile.dev

# Use an official Node.js image (Debian-based)
FROM node:22

# Set working directory
WORKDIR /app

# Install Netcat (nc) and clean up apt cache to reduce image size
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get install -y netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]