# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'  # Maps container's 5432 to host's 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb
      SENDGRID_API_KEY: your_sendgrid_api_key
    depends_on:
      - db
    command: npm run dev

volumes:
  db-data: